apps/models/urls.py
# django
from django.conf.urls import url
from django.views.generic import TemplateView
# project
from apps.utils.views import PopupFormView
from . import views
from .forms import CityForm

app_name = "modelforms"

urlpatterns = [
    url(
        r'^crea/ciudad$',
        PopupFormView.as_view(
            form_class=CityForm,
            template_name="forms/city-popup-form.html"
        ),
        name="create_city_popup"
    ),
    url(
        r'^crea/activo$',
        views.ActiveCreate.as_view(),
        name="create_active"
    ),
    url(
        r'^edita/activo/(?P<pk>.+)$',
        views.ActiveEdit.as_view(),
        name="edit_active"
    ),
    url(
        r'^relaciona/activo/(?P<pk>.+)$',
        views.ActiveRelate.as_view(),
        name="relate_active"
    ),
    url(
        r'^borra/activo/(?P<pk>.+)$',
        views.ActiveDelete.as_view(),
        name="delete_active"
    ),
    url(
        r'^bienvenido$',
        TemplateView.as_view(
            template_name='pages/initiative-success.html'
        ),
        name="welcome_initiative"
    ),
]

civics/urls.py
# Import django apps
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
# Import contrib apps
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView
# Import custom apps
from apps.users.views import ActivationView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('apps.api.urls')),
    url(r'^jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^$', TemplateView.as_view(template_name='pages/front.html'), name="front"),
    url(r'^', include('apps.models.urls')),

    # Static URLs
    url(r'^acerca$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^privacidad$', TemplateView.as_view(template_name='pages/privacy.html'), name="privacy"),

    # Registration URLs
    url(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^registrate/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name="registration_register"),
    url(r'^me-olvide-el-pass', auth_views.password_reset, name='password_reset'),
    url(r'^confirma-pass/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^pass-cambiado/$', auth_views.password_reset_complete, name="password_reset_complete"),
    url(r'^pass/ok/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'', include('registration.backends.default.urls')),
    url(r'^', include('apps.users.urls', namespace="users")),

    # Contact form
    url(r'^contacta/', include('contact_form.urls')),
]

if settings.DEBUG == True:
  urlpatterns += static( settings.STATIC_URL, document_root = settings.STATIC_ROOT )
  urlpatterns += static( settings.MEDIA_URL,  document_root = settings.MEDIA_ROOT )

templates/regions/footer.html
{# Toolbar region #} {% extends 'regions/region-base.html' %} {% load utils static i18n %}

{% block region_content %}
{% endblock %}

templates/regions/header.html
{# Header region #} {% extends 'regions/region-base.html' %}

{% block region_content %}{% endblock %}

templates/regions/messages.html
{# Messages region #} {% extends 'regions/region-base.html' %}

{% block region_content %}
    {% if messages %}
        <ul class="messages-list">
            {% for message in messages %}
                <li{% if message.tags %} class="messages-list__msg {{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/regions/region-base.html
{# Base template to render regions #}

<{{ html_container }} class="region-{{ region_name }}">
    <div class="container-{{ layout }}">
        {% block region_content %}{% endblock %}
    </div>
</{{ html_container }}>

templates/regions/toolbar.html
{# Toolbar region #} {% extends 'regions/region-base.html' %} {% load utils static i18n %}

{% block region_content %}
    <div class="region-{{ region_name }}__left">
        <figure class="civics-logo">
            <a href="{% url 'front' %}" title="{% trans 'Ir a la pantalla de inicio' %}">
                <h5>
                    MAPA DE ACTIVOS
                </h5>
            </a>
        </figure>
    </div>
    <div class="region-{{ region_name }}__center">
        
    </div>
    <div class="region-{{ region_name }}__right">
        <div class="navigation-trigger" onclick="document.querySelector('.region-toolbar__right').classList.toggle('active')">
            <p class="b1"></p><p class="b2"></p><p class="b3"></p>
        </div>
        <ul class="main-menu">
            <li class="main-menu__link main-menu__link--actives">
                <a href="/#!/activos">
                    {% trans 'Activos' %}
                </a>
            </li>
            <li class="main-menu__link main-menu__link--about">
                <a href="{% url 'about' %}">
                    {% trans 'Acerca' %}
                </a>
            </li>
        </ul>
        <ul class="user-actions">
            {% if request.user.is_authenticated %}
            <li class="user-actions__add-active">
                <a href="{% url 'modelforms:create_active' %}"
                   title="{% trans 'Añade un activo' %}">
                    <img src="{% static 'civics/img/icons/plus.svg' %}" />
                </a>
            </li>
            {% endif %}
            {% if request.user.is_staff %}
            <li class="user-actions__admin">
                    <a href="{% url 'admin:index' %}"
                       title="{% trans 'Administra' %}">
                        <img src="{% static 'civics/img/icons/settings.svg' %}" />
                    </a>
            </li>
            {% endif %}
            <li class="user-actions__io">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'auth_logout' %}"
                       title="{% trans 'Sal de la plataforma' %}">
                        <img src="{% static 'civics/img/icons/log-out.svg' %}" />
                    </a>
                {% else %}
                    <a href="{% url 'auth_login' %}"
                       title="{% trans 'Entra en la plataforma o regístrate en ella' %}">
                        <img src="{% static 'civics/img/icons/user.svg' %}" />
                    </a>
                {% endif %}
            </li>
        </ul>
    <div>
{% endblock %}