apps/users/urls.py
# django
from django.conf.urls import url, include
from django.views.generic import TemplateView
# project
from . import views

app_name = "users"

urlpatterns = [
    url(
        r'^gracias$',
        TemplateView.as_view(
            template_name='pages/goodbay.html'
        ),
        name='thanks'
    ),
    url(
        r'^sign-out/(?P<slug>.+)$',
        views.UserDelete.as_view(),
        name='signout'
    )
]

civics/urls.py
# Import django apps
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
# Import contrib apps
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView
# Import custom apps
from apps.users.views import ActivationView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('apps.api.urls')),
    url(r'^jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^$', TemplateView.as_view(template_name='pages/front.html'), name="front"),
    url(r'^', include('apps.models.urls')),

    # Static URLs
    url(r'^acerca$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^privacidad$', TemplateView.as_view(template_name='pages/privacy.html'), name="privacy"),

    # Registration URLs
    url(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^registrate/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name="registration_register"),
    url(r'^me-olvide-el-pass', auth_views.password_reset, name='password_reset'),
    url(r'^confirma-pass/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^pass-cambiado/$', auth_views.password_reset_complete, name="password_reset_complete"),
    url(r'^pass/ok/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'', include('registration.backends.default.urls')),
    url(r'^', include('apps.users.urls', namespace="users")),

    # Contact form
    url(r'^contacta/', include('contact_form.urls')),
]

if settings.DEBUG == True:
  urlpatterns += static( settings.STATIC_URL, document_root = settings.STATIC_ROOT )
  urlpatterns += static( settings.MEDIA_URL,  document_root = settings.MEDIA_ROOT )

apps/users/views.py
# django
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render
from django.views import View
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import DeleteView
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import send_mail
# contrib
from registration.views import ActivationView as BaseActivationView
from registration.models import RegistrationProfile
from registration import signals
# project
from apps.models.models import City, Active
from apps.models import categories
from django.conf import settings


class ActivationView(BaseActivationView):
    """
    Custom activation view that redirects user to Create Initiative form

    """

    registration_profile = RegistrationProfile

    def activate(self, *args, **kwargs):
        """
        Given an an activation key, look up and activate the user
        account corresponding to that key (if possible).

        After successful activation, the signal
        ``registration.signals.user_activated`` will be sent, with the
        newly activated ``User`` as the keyword argument ``user`` and
        the class of this backend as the sender.

        """
        activation_key = kwargs.get('activation_key', '')
        site = get_current_site(self.request)
        activated_user = (
            self.registration_profile.objects.activate_user(
                activation_key,
                site
            )
        )
        if activated_user:
            signals.user_activated.send(
                sender=self.__class__,
                user=activated_user,
                request=self.request
            )
        return activated_user

    def get_success_url(self, user):
        return ('modelforms:create_active', (), {})

class UserDelete(DeleteView):

    model = User
    template_name = 'users/user_confirm_delete.html'
    success_url = reverse_lazy('users:thanks')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, _('Tu cuenta ha sido cancelada'))
        pk = request.user.pk
        mail = User.objects.get(pk=pk).email
        send_mail(
            _('Tu cuenta eha sido cancelada'),
            _('Te confirmamos que la cuenta '
              'asociada a este correo ha sido borrada con éxito. '
              'Este es un correo automático. No lo respondas.'
             ),
            'no-reply',
            [mail]
        )
        return super(UserDelete, self).delete(request, *args, **kwargs)

    def get_object(self):
        pk = self.request.user.pk
        return User.objects.get(pk=pk)

templates/users/dashboard.html
{# Staff user dashboard #}
{% extends 'layouts/single-fluid-column.html' %}
{% load utils  i18n static imagekit leaflet_tags users %}
{% block body_classes %}dashboard{% endblock %}

{% block page_header %}
  {% leaflet_css %}
  <meta name="google-signin-client_id" content="{{ google_client_id }}"></meta>
{% endblock %}

{% block main %}
    {% trans 'Mi perfil' as page_title %}
    <a href="{% url 'users:signout' 'me' %}" class="user-delete">
        {% trans 'Cancelar mi usuario' %}
    </a>
    {% include 'pages/title.html' with title=page_title %}
    <div class="dashboard-left">
        <div class="dashboard-left__left">
            <div class="initiatives--dashboard">
                <div class="initiatives--dashboard__title">
                    <h2>{% trans 'Mis iniciativas' %}</h2>
                     <span class="initiatives--dashboard__count">({{ initiatives|length }})</span>
                     <a class="initiatives--dashboard__create" title="{% trans 'Crea una iniciativa' %}"
                        href="{% url 'modelforms:create_initiative' %}">
                        <span class="icon-add"></span>
                     </a>
                </div>
                <div class="initiatives--dashboard__items">
                    {% for initiative in initiatives %}
                    <a href="{% url 'modelforms:edit_initiative' initiative.pk %}">
                        <div class="initiatives--dashboard__item">
                            <figure class="initiatives--dashboard__item-image">
                                {% if initiative.image %}
                                    {% thumbnail '100x100' initiative.image %}
                                {% else %}
                                    <span class="icon-agent"></span>
                                {% endif %}
                            </figure>
                            <div>
                                <h5 class="initiatives--dashboard__item-name">
                                    {{ initiative.name }}
                                </h5>
                                <div class="initiatives--dashboard__item-date">
                                    {% trans 'Fecha de alta:' %} {{ initiative.creation_date }}
                                </div>
                            </div>
                            <p class="initiatives--dashboard__edit">
                                {% trans 'Editar' %}
                            </p>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="dashboard-right">
        <div class="events-map--dashboard__title">
            <h2>{% trans 'Mapa de iniciativas' %}</h2>
        </div>
        {% leaflet_map "dashboard_map" %}
    </div>
{% endblock %}

{% block page_scripts %}
    <!-- Dependencies -->
    {% leaflet_js %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <!-- Populate map. See apps.users.templatetags -->
    {% dashboard_leaflet_js user_initiatives=initiatives %}
    <!-- Import events. See apps.users.templatetags -->
    {% events_import_js user_id=request.user.id user_initiatives=initiatives %}
{% endblock %}

templates/users/user_confirm_delete.html
{# Staff user dashboard #}
{% extends 'layouts/single-fluid-column.html' %}
{% load utils i18n %}
{% block body_classes %}signout{% endblock %}


{% block main %}
    {% trans 'Signout' as page_title %}
    <form class="user-delete-form" action="" method="POST">
        {% csrf_token %}
        <p class="user-delete-form__text">
        {% blocktrans trimmed %}
        ¿Estás seguro de que quieres cancelar tu cuenta?
        Esta acción no se puede deshacer y borrará a tu usuario y a todo el
        contenido asociado al mismo.
        {% endblocktrans %}
        </p>
        {{ form }}
        <input type="submit" value="{% trans 'Cancela mi cuenta' %}"></input>
        <a href="{% url 'front' %}">
            {% trans 'Volver atrás' %}
        </a>
    </form>
{% endblock %}